- .gitignore
- models/user.js
- public/js/script.js
- public/stylesheets/style.css
- routes/index.js
- routes/users.js
- views/admin.pug
- views/index.pug
- views/layout.pug
- views/login.pug
- views/profile.pug
The different looks kind of huge, but it's really because I fixed all the indentation here as well.
> Updates to admin and overall pages

- models/token.js
- routes/users.js
- views/index.pug
- views/layout.pug
- views/users.pug
Issue #9 
You'll need to add the two keys to your env.json below (this is because nodemailer sends the email from this account. You'll need to go to : https://www.google.com/settings/security/lesssecureapps and set the Access for less secure apps setting to Enable):
{
"email": your gmail here,
"password": your gmail password here
}
> Implemented issue #9 : Email verification when creating accounts

- app.js
- models/user.js
- public/js/script.js
- public/stylesheets/style.css
- routes/users.js
- views/ingredients.pug
- views/layout.pug
Resolved issue #28 
Added client side javascript to call in individual pages to check if user is an admin.
Regarding the client side admin check, we'll eventually want to change this as even using the CSS display none still leaves the html visible in the dev tools.
> Authentication fix; client side admin check

- routes/vendors.js
- views/vendors.pug
Now actually lets you see the vendors rather than having to know the code (sorry).  Next is to add search
> Vendor UI Tweaks

- .gitignore
- app.js
- models/user.js
- public/js/script.js
- routes/users.js
- views/inventory.pug
- views/profile.pug
- views/users.pug
> Fix UI for inventory and admin/non admin view. Get rid of password confirmation

- helpers/seed.js
- routes/inventory_routes.js
- routes/users.js
- views/inventory.pug
Updated setup script to set default limit values.
Prefill form with existing limit values.
> Small inventory updates

- routes/ingredients.js
hopefully this will fix unhandled promise rejection errors
> changed all query callbacks to promises

- example.csv
- package-lock.json
- package.json
- routes/files.js
- routes/vendors.js
@Lucytheanimefan : The ingredient added has 0 amount, and the "amount" field in the csv goes to the vendor. FYI if you wanna demo it.
@teddyf : I changed the vendor add_ingredient routes a little bit for the bulk import. I tested it, and it seemed like it was still working, but you should probably check to make sure.
> implemented bulk import

- routes/files.js
- routes/ingredients.js
Bulk import: no longer creates any stock in inventory or available units for the vendor.
Ingredients: changed names to match input case.
> updating some things to match requirements

- app.js
- package-lock.json
- package.json
- public/js/script.js
- routes/duke_oauth.js
- routes/index.js
- routes/users.js
- views/index.pug
- views/layout.pug
- views/login.pug
- views/profile.pug
There's a link to login with netid, doesn't really do anything beyond that yet. This PR is mainly for getting oauth functionality done. Other stuff will be done in a new users UI focused PR.
> oauth2 basic routes

- helpers/seed.js
- helpers/variables.js
- models/user.js
- public/js/material-dashboard.js
- public/js/script.js
- routes/duke_oauth.js
- routes/users.js
- views/ingredient.pug
- views/ingredients.pug
- views/inventory.pug
- views/layout.pug
- views/profile.pug
- views/users.pug
- views/vendor.pug
- views/vendors.pug
Resolved issue #87 and #88.  
Ideally all the different user permissions are done.
> Mostly done with user management

- app.js
- helpers/mongo_helpers.js
- helpers/variables.js
- models/ingredient.js
- models/log.js
- models/user.js
- public/stylesheets/style.css
- routes/duke_oauth.js
- routes/ingredients.js
- routes/logs.js
- routes/users.js
- routes/vendors.js
- views/layout.pug
- views/log.pug
- views/logs.pug
- views/user.pug
- views/users.pug
- views/vendor.pug
Added to users, vendor, and ingredients. Although will likely be redone for vendor once vendor refactor is pushed.
> Global logging

- helpers/ingredients.js
- routes/ingredients.js
- views/ingredient.pug
- views/ingredients.pug
> added way to associate vendors to ingredient from ingredient page

- example.csv
- helpers/ingredients.js
- package-lock.json
- package.json
- routes/files.js
- routes/ingredients.js
fixes #77 and handles adding new ingredient.
> Ev2 ingredient bulk import (TODO: formula)

- example_formula.csv
- helpers/ingredients.js
- routes/ingredients.js
- views/ingredient.pug
> Ingredient vendor fix

- helpers/vendor.js
- models/vendor.js
- routes/vendors.js
All my changes were within vendors so i doubt there should be any conflict
> fixes issue with deleting ingredients and updating catalogue

- helpers/ingredients.js
- helpers/inventory.js
- models/ingredient.js
- models/user.js
- public/js/script.js
- public/stylesheets/style.css
- routes/files.js
- routes/formulas.js
- routes/ingredients.js
- routes/inventory_routes.js
- routes/vendors.js
- views/formula.pug
- views/layout.pug
- views/log.pug
Added an API call to ingredient to get ingredient json data from it's mongo id
> Added logging to formula & ingredient

- models/user.js
- public/js/script.js
- routes/users.js
If your account doesn't exist, creates account and automatically logs you in and redirects you to profile page
> Netid login fix

- routes/ingredients.js
> abort deletion if an ingredient is being used in a formula

- views/formula.pug
- views/formulas.pug
- views/ingredients.pug
- views/vendor.pug
#116 
might need to do this for formulas and vendors too?
> Fix escape characters like % in ingredients

- views/ingredients.pug
- views/logs.pug
> Check if log description exists

- helpers/ingredients.js
- helpers/users.js
- routes/users.js
- views/report.pug
i added a helper method in userhelper to help calculate all the things and update the ingredient+spending report when we checkout
> update ingredient on checkout

- example_formula.csv
- public/js/script.js
- routes/files.js
- routes/ingredients.js
- routes/users.js
- routes/vendors.js
- views/log.pug
Changes in ingredient, vendor and user
> Need to link to entity from logs

- helpers/ingredients.js
- routes/files.js
- routes/ingredients.js
- routes/vendors.js
- views/formula-confirmation.pug
> Logging and made the add to cart a post request

- views/ingredient.pug
not sure if this should be manager or admin
> change associate vendor to manager+ only

- helpers/ingredients.js
- helpers/inventory.js
- helpers/variables.js
- models/ingredient.js
- views/ingredient.pug
- views/vendor.pug
> Some ev2 fixes (issues are in comment)

- .gitignore
- app.js
- helpers/variables.js
- package-lock.json
- package.json
- public/js/jquery.tablesorter.pager.js
- routes/backups.js
- views/backups.pug
What's not done: 
* better UI
* More complex backup scheduling per requirements
* No backup restore. TBD if necessary, Piazza post pending.  
Right now:
* Schedule backups once per day with node-schedule. 
* You can click a backup and download the tar.
> Basic backup implementation done

- models/user.js
- public/js/script.js
- routes/users.js
- views/layout.pug
> Login changes

- models/log.js
- routes/logs.js
- views/layout.pug
- views/logs.pug
Uses the checkout cart arrow UI that @amanocha came up with
> Fix log pagination

- helpers/ingredients.js
- helpers/variables.js
- models/ingredient.js
- models/vendor.js
- routes/ingredients.js
- views/ingredient.pug
- views/ingredients.pug
hurray, still have to make intermediate product ingredient things
#183
> updated ingredient schema (new lots, intermediate product field, FIFO)

- helpers/variables.js
- routes/backups.js
- views/backups.pug
> Backup restore fix

- models/recall.js
- public/js/script.js
- routes/users.js
- views/lot_selection.pug
you can ignore recall.js.  was starting it and realised i also pushed it. there isn't anything besids a possible structure on it. have not written any of the functions
> now adds to lots by package

- helpers/variables.js
- routes/backups.js
- routes/formulas.js
- routes/ingredients.js
- routes/logs.js
- routes/vendors.js
- views/backups.pug
- views/ingredients.pug
- views/logs.pug
- views/vendors.pug
Not added to your parts of the code just yet.
> Can no longer do infinite pagination for logs

- helpers/ingredients.js
- helpers/variables.js
- models/real_recall.js
- routes/reports.js
- views/recall.pug
- views/report.pug
> Recall report fix

- app.js
- models/formula.js
- models/production_line.js
- public/js/script.js
- routes/formulas.js
- routes/production_lines.js
- views/layout.pug
- views/production_line.pug
- views/production_lines.pug
Wow I finished this 15 minutes ahead of my anime release time!
> Basic production lines CRUD functionality

- models/log.js
- routes/logs.js
- views/log.pug
- views/logs.pug
> Log filtering fix

- models/vendor.js
> fixes case insensitive bug

- helpers/formula.js
- helpers/ingredients.js
- helpers/variables.js
- models/freshness.js
- public/js/script.js
- routes/formulas.js
- routes/reports.js
- routes/users.js
- views/cart.pug
- views/checkout.pug
- views/edit_cart.pug
- views/formula-confirmation.pug
- views/formula.pug
- views/formulas.pug
- views/ingredient.pug
- views/ingredients.pug
- views/lot_selection.pug
- views/report.pug
should be all good but someone else should test too in case i'm crazy
> fixed formula bug and clarified labels

- app.js
- helpers/variables.js
- models/formula.js
- models/production_line.js
- public/js/script.js
- public/stylesheets/style.css
- routes/formulas.js
- routes/production_lines.js
- views/formula.pug
- views/layout.pug
- views/production_line.pug
- views/production_lines.pug
* CRUD
* Formula to production line mapping from production line view and formula view
> Basic production line functionality DON'T MERGE TIL AFTER DEMO

- app.js
- helpers/final_products.js
- helpers/formula.js
- helpers/ingredients.js
- helpers/users.js
- models/final_product.js
- models/formula.js
- models/ingredient.js
- models/production_line.js
- models/user.js
- routes/distributor.js
- routes/formulas.js
- routes/production_lines.js
- views/distributor.pug
- views/layout.pug
Distribution network stuff, created a new schema+route. still need to do distribution network reports (the profitability report looks like a massive pain)
@Lucytheanimefan I also added the inventory update stuff for production lines
> Distribution network + Production line inventory update

- helpers/ingredients.js
- models/completed_production.js
- models/production_line.js
- routes/formulas.js
- routes/production_lines.js
- views/completed_products.pug
- views/formulas.pug
- views/layout.pug
-2 annoying scroll bars -> 1 more convenient one (probably the most important change here)
-added lot number to alert message
> completed production tab stuff (filtering + being able to mark productions complete)

- routes/formulas.js
- routes/reports.js
- views/formula-confirmation.pug
* Show alert if no available production lines
* Fix issue for case where production line was created after the user specified start date for production efficiency chart
> Show alert if no available production lines

- routes/formulas.js
- views/log.pug
Also fixed individual log view
> Add links to sending formula to production line log

- helpers/variables.js
- public/js/script.js
- routes/orders.js
> Order stuff
